### ISSUE TITLE
Detach in neuro-flow

### ISSUE THREAD

**Issue by mariyadavydova** [neuromation/neuro-flow#72]
Please make it clear and consistent with neuro: I'd like to have a shortcut to detach from a job in a live mode, and I'd like to see a shortcut for this action in the job's output.

**Comment by asvetlov** [comment]
I don't follow what shortcut are you talking about.
The current behavior looks like the following:
```
$ neuro-flow run bash
√ Job ID: job-0ea1c9cf-cfff-4003-9f69-3eefe57d2a75 
- Status: pending Creating
- Status: pending Scheduling
√ Status: running
√ Http URL: https://job-0ea1c9cf-cfff-4003-9f69-3eefe57d2a75.jobs-dev.neu.ro
√ The job will die in a day. See --life-span option documentation for details.
√ =========== Job is running in terminal mode ===========
√ (If you don't see a command prompt, try pressing enter)
√ (Use Ctrl-P Ctrl-Q key sequence to detach from the job)
root@job-0ea1c9cf-cfff-4003-9f69-3eefe57d2a75:/# 
```
A hint for `Ctrl-P + Ctrl-Q` is displayed as you can see

**Comment by mariyadavydova** [comment]
Yes, I checked once again, it is displayed and it works. Sorry for false alarm.
